### ISSUE TITLE
margins do not support 0

### ISSUE THREAD

**Issue by kplatter** [jsreport/toner-wkhtmltopdf#2]
because the margins are checked with if (options.marginLeft),  (0 ZERO) does not return true and does not get passed to wkhtmltopdf.  The closest you can get to 0 is 1mm.

perhaps instead we could use if (!isNaN(Number(o.marginLeft)))

```
        wkhtmltopdf: {
           marginLeft: 0,
           marginRight: 0,
           marginTop: 0,
           marginBottom: 0
        }
```

**Comment by pofider** [comment]
I implemented this but then realized you can just set 0mm string to the values and you are done.

``` js
wkhtmltopdf: {
           marginLeft: "0mm",
           marginRight: "0mm",
           marginTop: "0mm",
           marginBottom: "0mm"
        }
```

So the fix is not required, right?

**Comment by kplatter** [comment]
The default unit is mm, so I think it would still be good to implement in case someone does not specify like me.  The supported units in pdfsettings.cc are 

default, mm, millimeter
cm,centimeter
m,meter
didot
in,inch
pc,pica
cicero
px,pixel
pt,point

**Comment by pofider** [comment]
Ok, done.

You can check the commit.

**Comment by kplatter** [comment]
Looks good, thx.  Go ahead and close issue.
