### ISSUE TITLE
Can we update the wkhtmltopdf-installer dependency?

### ISSUE THREAD

**Issue by dlong500** [jsreport/toner-wkhtmltopdf#3]
Now that the `wkhtmltopdf-installer` module had its dependencies updated with the 0.2.0 release (see pofider/node-wkhtmltopdf-installer#2), can we update that dependency here?

I could do a PR, but for such a small update I thought it might be easier for you to just bump that dependency version.

Thanks.

**Comment by pofider** [comment]
Done.
